ENH: Support -x|--line-regexp
This cannot be passed directly to grep, because it would prevent the matching of the separator (unfiltered) lines.
For normal pattern matching, all we need to do is add the ^\(...\)$ anchors.
For literal matching, we delegate the escaping to toLiteralRegexp, which conveniently understands all regexp dialects (which are now parsed separately into grepRegexpDialectArgs).

diff --git a/bin/fieldGrep b/bin/fieldGrep
--- a/bin/fieldGrep
+++ b/bin/fieldGrep
@@ -19,8 +19,24 @@ HELPTEXT
     printf 'Usage: %q %s\n' "$(basename "$1")" '-i|--input FILESPEC [...] -V|--invert-fields GREP-OPTIONS [...] [-]N [...] [-?|-h|--help]'
 }
 
+addPattern()
+{
+    if [ "$isLineRegexp" ]; then
+	if [ "$isFixedStrings" ]; then
+	    literalPattern="$(toLiteralRegexp "${grepRegexpDialectArgs[@]}" --line-regexp "$2")" || exit 3
+	    grepPatternArgs+=("$1" "$literalPattern")
+	    grepFixedStringsArgs=()
+	else
+	    grepPatternArgs+=("$1" "^\\(${2}\\)\$")
+	fi
+    else
+	grepPatternArgs+=("$1" "$2")
+    fi
+}
+
 isBuffered=t
 typeset -a grepArgs=()
+typeset -a grepRegexpDialectArgs=()
 typeset -a grepBufferedArgs=()
 [ -t 1 ] && grepBufferedArgs=(--line-buffered)
 typeset -a grepPatternArgs=()
@@ -32,25 +48,28 @@ isInvertFields=
 isOnlyMatching=
 isPerlRegexp=
 isFixedStrings=
+typeset -a grepFixedStringsArgs=()
+isLineRegexp=
 isWordRegexp=
 while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)		shift; printUsage "$0"; exit 0;;
 
-	-+([EGi]))		grepArgs+=("$1"); shift;;
-	--@(extended-regexp|basic-regexp|ignore-case))
-				grepArgs+=("$1"); shift;;
-	--fixed-strings)	grepArgs+=("$1"); [ "$fieldSeparator" = '[	 ]' ] && fieldSeparator=' '; shift; isFixedStrings=t;;
-	--perl-regexp|-P)	grepArgs+=("$1"); isPerlRegexp=t; shift;;
+	-+([EG]))		grepRegexpDialectArgs+=("$1"); shift;;
+	--@(extended-regexp|basic-regexp))
+				grepRegexpDialectArgs+=("$1"); shift;;
+	--perl-regexp|-P)	grepRegexpDialectArgs+=("$1"); isPerlRegexp=t; shift;;
+
+	--ignore-case|-i)	grepArgs+=("$1"); shift;;
+	--fixed-strings)	grepFixedStringsArgs+=("$1"); shift; isFixedStrings=t;;
 	--word-regexp|-w)	grepArgs+=("$1"); separatorGrepArgs=(-e '^[0-9][0-9]*'); shift; isWordRegexp=t;;    # A (usually) non-word separator won't be matched; need to aim for the leading field number to include the unfiltered fields.
-	--line-regexp|-x)	echo >&2 'ERROR: -x|--line-regexp is not supported; use explicit anchoring with ^ and $.'
-				exit 2
-				;;
+	--line-regexp|-x)	shift; isLineRegexp=t;;
 	--invert-match|-v)	grepArgs+=("$1"); separatorGrepArgs=(); shift;;	# Because of the inversion, we must not match the separators now so that they get included.
 	--only-matching|-o)	grepArgs+=("$1"); isOnlyMatching=t; shift;;
-	--regexp|-e)		grepPatternArgs+=("$1" "$2"); shift; shift;;
-	--regexp=*)		grepPatternArgs+=(--regexp "${1#--regexp=}"); shift;;
+
+	--regexp|-e)		addPattern "$1" "${2:?}"; shift; shift;;
+	--regexp=*)		addPattern --regexp "${1#--regexp=}"; shift; shift;;
 	--file|-f)		grepPatternArgs+=("$1" "$2"); shift; shift;;
 	--file=*)		grepPatternArgs+=("$1"); shift;;
 
@@ -64,6 +83,11 @@ do
 	*)			break;;
     esac
 done
+if [ ${#grepFixedStringsArgs[@]} -gt 0 ]; then
+    # When literal matching is active (and not just emulated as with --line-regexp),
+    # the field separator pattern must be converted to a literal space.
+    [ "$fieldSeparator" = '[	 ]' ] && fieldSeparator=' '
+fi
 if [ ${#grepPatternArgs[@]} -eq 0 ]; then
     echo 'ERROR: No PATTERN(s) passed.'
     echo
@@ -73,6 +97,9 @@ elif [ $# -eq 0 ]; then
     echo 'ERROR: No field number N passed.'
     echo
     printUsage "$0"
+    exit 2
+elif [ "$isLineRegexp" ] && [ "$isWordRegexp" ]; then
+    echo 'ERROR: -l|--line-regexp cannot be combined with -w|--word-regexp.'
     exit 2
 elif [ "$isFixedStrings" ] && [ "$isWordRegexp" ]; then
     echo 'ERROR: --fixed-strings cannot be combined with -w|--word-regexp.'
@@ -137,7 +164,7 @@ NR == 1 {
     if (isUnBuffered) fflush()
 }
 ' "${awkArgs[@]}" | \
-    grep "${grepArgs[@]}" "${grepBufferedArgs[@]}" "${separatorGrepArgs[@]}" "${grepPatternArgs[@]}" | \
+    grep "${grepRegexpDialectArgs[@]}" "${grepFixedStringsArgs[@]}" "${grepArgs[@]}" "${grepBufferedArgs[@]}" "${separatorGrepArgs[@]}" "${grepPatternArgs[@]}" | \
 awk "${fsArgs[@]}" \
     -v "isBuffered=$isBuffered" \
 '
