fieldsToArgs: FIX: Actually use runWith if any runWithPrompt args are given (cp. inkarkat/shell-tools@c3b95ab)
The default $runWithCommand never saw action because $with is only changed by --with-prompt. Do away with a separate $runWithCommand and use $with for the selection as well.
Robustness: Handle with=header via fall-through and assert on unknown $what values.

(This relates to commit inkarkat/shell-tools@c3b95abe6d20db779acd5fd6077993880cc6b5b0)

diff --git a/bin/fieldsToArgs b/bin/fieldsToArgs
--- a/bin/fieldsToArgs
+++ b/bin/fieldsToArgs
@@ -77,7 +77,6 @@ with=
 errorRedir='2>&1'
 typeset -a colorArg=()
 betweenCommand=
-runWithCommand=runWith
 typeset -a runWithPromptArgs=()
 while [ $# -ne 0 ]
 do
@@ -99,12 +98,12 @@ do
 			shift; errorRedir='';;
 	--no-color|--color=*)	colorArg=("$1"); shift;;
 	--color)		colorArg=("$1" "$2"); shift; shift;;
-	--with-prompt)	shift; with=prompt; runWithCommand=runWithPrompt;;
+	--with-prompt)	shift; with=runWithPrompt;;
 
 	--trailing-prompt|--no-trailing-prompt|--no-output-no-prompt|--no-output-no-error|--no-success-no-count|--exit-on-success|--exit-on-failure|--emulate-prompt|--worst-status)
-			runWithPromptArgs+=("$1"); shift;;
+			runWithPromptArgs+=("$1"); shift; : ${with:=runWith};;
 	--initial-status|--no-count-on|--exit-on|--exit-unless|--comment|--summarize-failed|--summarize-failed-separator)
-			runWithPromptArgs+=("$1" "$2"); shift; shift;;
+			runWithPromptArgs+=("$1" "$2"); shift; shift; : ${with:=runWith};;
 	--between-command)
 			shift; betweenCommand="$1"; shift;;
 
@@ -129,7 +128,7 @@ if [ ${#commands[@]} -eq 0 ]; then
     echo
     printUsage "$0"
     exit 2
-elif [ ${#runWithPromptArgs[@]} -gt 0 -a "$with" = header ]; then
+elif [ ${#runWithPromptArgs[@]} -gt 0 -a "$with" = 'header' ]; then
     echo 'ERROR: Cannot combine runWith[Prompt] arguments with --with-header.'
     echo
     printUsage "$0"
@@ -205,8 +204,9 @@ buildHeaderAndInterpolatedCommands()
 }
 
 isFirst=t
+isHeader=
 case "$with" in
-    prompt)
+    runWith*)
 	[ ${#runWithPromptArgs[@]} -eq 0 ] && runWithPromptArgs=(--worst-status)
 	quoter='%q'; [ "$isNeedEval" ] && quoter='%s'
 	parseFields | while IFS=$'\n' read -r argCnt
@@ -227,12 +227,13 @@ case "$with" in
 	    printf "$quoter " "${interpolatedCommands[@]}"
 	    printf '\n'
 	    isFirst=
-	done | ${runWithCommand:?} "${runWithPromptArgs[@]}"
+	done | ${with:?} "${runWithPromptArgs[@]}"
 	;;
-    *)
+    header)
+	isHeader=t;&
+    '')
 	status=0
 	: ${FIELDSTOARGS_HEADER_ID:="fieldsToArgs-$$-$RANDOM"}
-	isHeader=; [ "$with" = 'header' ] && isHeader=t
 	exec 3<&0
 	while IFS=$'\n' read -r argCnt
 	do
@@ -256,4 +257,5 @@ case "$with" in
 	done < <(parseFields)
 	exit $status
 	;;
+    *)	printf >&2 'ASSERT: Invalid strategy: %s\n' "$with"; exit 3;;
 esac
