ENH: UI: Consistency: Also support --input-files FILE [...] ;
This is useful with shell globbing.

diff --git a/bin/field b/bin/field
--- a/bin/field
+++ b/bin/field
@@ -1,18 +1,20 @@
 #!/bin/bash
 shopt -qs extglob
 
+: ${FIELD_INPUTFILES_END=;}
+
 printUsage()
 {
     cat <<HELPTEXT
 Print selected field(s) N (-N counted from behind) from stdin, separated by SEP (or the original FS).
 HELPTEXT
     printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[-F|--field-separator FS] [-u|--unbuffered] [-]N|SEP [...]'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '-i|--input FILESPEC [...] [-]N|SEP [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" "... -i|--input FILE [-i ...]|--input-files FILE [...] ${FIELD_INPUTFILES_END} [-]N|SEP [...] [-?|-h|--help]"
     cat <<HELPTEXT
 Print everything but passed field(s) N (-N counted from behind) from stdin.
 HELPTEXT
     printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[-F|--field-separator FS] [-u|--unbuffered] -v|--remove [-]N [...]'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '-i|--input FILESPEC [...] -v|--remove [-]N [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" "... -i|--input FILE [-i ...]|--input-files FILE [...] ${FIELD_INPUTFILES_END} -v|--remove [-]N [...] [-?|-h|--help]"
 }
 fieldNumberError()
 {
@@ -24,20 +26,38 @@ fieldNumberError()
 
 isBuffered=t
 typeset -a fsArgs=()
-typeset -a awkArgs=()
+typeset -a inputFilespecs=()
 isRemoveFields=
 while [ $# -ne 0 ]
 do
     case "$1" in
-	--help|-h|-\?)		shift; printUsage "$0"; exit 0;;
-	--input|-i)		shift; awkArgs+=("$1"); shift;;
-	--remove|-v)		shift; isRemoveFields=t;;
-	--field-separator|-F)	shift; fsArgs=(-F "$1"); shift;;
-	--unbuffered|-u)	shift; isBuffered=;;
-	--)			shift; break;;
-	-+([0-9]))		break;;
-	-*)			{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
-	*)			break;;
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--input|-i)	shift; inputFilespecs+=("${1:?}"); shift;;
+	--input-files)	shift
+			while [ $# -gt 0 -a "$1" != "$FIELD_INPUTFILES_END" ]
+			do
+			    inputFilespecs+=("$1")
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --input-files must be concluded with '${FIELD_INPUTFILES_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			if [ ${#inputFilespecs[@]} -eq 0 ]; then
+			    echo 'ERROR: --input-files must be followed by at least one FILE.'; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			;;
+	--remove|-v)	shift; isRemoveFields=t;;
+	--field-separator|-F)
+			shift; fsArgs=(-F "$1"); shift;;
+	--unbuffered|-u)
+			shift; isBuffered=;;
+	--)		shift; break;;
+	-+([0-9]))	break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
     esac
 done
 [ $# -gt 0 ] || fieldNumberError
@@ -85,7 +105,7 @@ BEGIN {
     printf "%s", ORS
     if (! isBuffered) fflush()
 }
-' "${awkArgs[@]}"
+' "${inputFilespecs[@]}"
 else
     hasFieldNumber=
     isSubsequent=
@@ -124,5 +144,5 @@ $outputSeparatorDetermination
 {
     print$selectors
     if (! isBuffered) fflush()
-}" "${awkArgs[@]}"
+}" "${inputFilespecs[@]}"
 fi
diff --git a/bin/fieldDefault b/bin/fieldDefault
--- a/bin/fieldDefault
+++ b/bin/fieldDefault
@@ -1,12 +1,14 @@
 #!/bin/bash
 
+: ${FIELDDEFAULT_INPUTFILES_END=;}
+
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
     printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[-F|--field-separator FS] [-u|--unbuffered] [-n|--field-num N] -v|--value VAL LIST [...] [[-v|--value VAL] LIST ...]'
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" '-i|--input FILESPEC [...] [-i[SUFFIX]|--in-place[=SUFFIX]] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" "... -I|--input FILE [-I ...]|--input-files FILE [...] ${FIELDDEFAULT_INPUTFILES_END} [-i[SUFFIX]|--in-place[=SUFFIX]] [-?|-h|--help]"
 }
 printUsage()
 {
@@ -28,17 +30,23 @@ HELPDESCRIPTION
     echo
     printShortUsage "$1"
     cat <<HELPTEXT
-    --field-separator|-F FS Use FS as the input field separator (as with AWK).
-    --unbuffered|-u	    Immediately output each read line.
-    --field-num|-n N	    Use a fixed number N of fields for addressing fields
-			    from behind (instead of taking the maximum number
-			    encountered so far). When a particular line has more
-			    fields, that number is used only for addressing
-			    within that line.
-    --value|-v VAL	    Default the following ranges denoted by LIST to VAL.
+    --field-separator|-F FS
+			Use FS as the input field separator (as with AWK).
+    --unbuffered|-u	Immediately output each read line.
+    --field-num|-n N	Use a fixed number N of fields for addressing fields
+			from behind (instead of taking the maximum number
+			encountered so far). When a particular line has more
+			fields, that number is used only for addressing within
+			that line.
+    --value|-v VAL	Default the following ranges denoted by LIST to VAL.
     --in-place[=SUFFIX]|-i[SUFFIX]
-			    Edit FILESPEC(s) in place (makes backup if SUFFIX
-			    supplied).
+			Edit FILESPEC(s) in place (makes backup if SUFFIX
+			supplied).
+    --input|-I FILE 	Read from FILE(s) instead of standard input.
+    --input-files FILE [...] ${FIELDDEFAULT_INPUTFILES_END}
+			Read from the following FILE(s) i.e. all following
+			arguments until an argument consisting of '${FIELDDEFAULT_INPUTFILES_END}'
+			is encountered instead of standard input.
 EXIT STATUS:
     0	Complete success.
     1	AWK processing error.
@@ -54,7 +62,7 @@ isBuffered=t
 fieldNum=
 typeset -a awkCall=(awk)
 typeset -a awkArgs=()
-typeset -a awkFiles=()
+typeset -a inputFilespecs=()
 typeset -a values=()
 typeset -a fields=()
 unset currentValue
@@ -64,7 +72,23 @@ while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
-	--input|-i)	shift; awkFiles+=("$1"); shift;;
+	--input|-I)	shift; inputFilespecs+=("${1:?}"); shift;;
+	--input-files)	shift
+			while [ $# -gt 0 -a "$1" != "$FIELDDEFAULT_INPUTFILES_END" ]
+			do
+			    inputFilespecs+=("$1")
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --input-files must be concluded with '${FIELDDEFAULT_INPUTFILES_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			if [ ${#inputFilespecs[@]} -eq 0 ]; then
+			    echo 'ERROR: --input-files must be followed by at least one FILE.'; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			;;
 	--field-separator|-F)
 			shift; awkArgs=(-F "$1"); shift;;
 	--unbuffered|-u)
@@ -188,4 +212,4 @@ NR == 1 {
     print
     if (! isBuffered) fflush()
 }
-' "${awkFiles[@]}"
+' "${inputFilespecs[@]}"
diff --git a/bin/fieldGrep b/bin/fieldGrep
--- a/bin/fieldGrep
+++ b/bin/fieldGrep
@@ -2,6 +2,8 @@
 set -o pipefail
 shopt -qs extglob
 
+: ${FIELDGREP_INPUTFILES_END=;}
+
 printUsage()
 {
     cat <<HELPTEXT
@@ -9,14 +11,14 @@ Print lines where selected field(s) N (-N counted from behind), separated by FS,
 HELPTEXT
     echo
     printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[-F|--field-separator FS] [-u|--unbuffered] [GREP-OPTIONS ...] -e|--regexp PATTERN|-f|--file FILE [...] [-]N [...]'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '-I|--input FILESPEC [...] GREP-OPTIONS [...] [-]N [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" "... -I|--input FILE [-i ...]|--input-files FILE [...] ${FIELDGREP_INPUTFILES_END} GREP-OPTIONS [...] [-]N [...] [-?|-h|--help]"
     echo
     cat <<HELPTEXT
 Print lines where any but the passed field(s) N (-N counted from behind), separated by FS, match a PATTERN.
 HELPTEXT
     echo
     printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[-F|--field-separator FS] [-u|--unbuffered] -V|--invert-fields [GREP-OPTIONS ...] -e|--regexp PATTERN|-f|--file FILE [...] [-]N [...]'
-    printf 'Usage: %q %s\n' "$(basename "$1")" '-I|--input FILESPEC [...] -V|--invert-fields GREP-OPTIONS [...] [-]N [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" "... -I|--input FILE [-i ...]|--input-files FILE [...] ${FIELDGREP_INPUTFILES_END}-V|--invert-fields GREP-OPTIONS [...] [-]N [...] [-?|-h|--help]"
 }
 
 addPattern()
@@ -64,7 +66,7 @@ typeset -a grepPatternArgs=()
 unset separatorGrepArgs
 typeset -a fsArgs=()
 fieldSeparator='[	 ]'
-typeset -a awkArgs=()
+typeset -a inputFilespecs=()
 isInvertFields=
 isOnlyMatching=
 isPerlRegexp=
@@ -94,7 +96,23 @@ do
 	--file|-f)		addPatternFile "$1" "$2"; shift; shift;;
 	--file=*)		addPatternFile --file "${1#--file=}"; shift;;
 
-	--input|-I)		shift; awkArgs+=("$1"); shift;;
+	--input|-I)	shift; inputFilespecs+=("${1:?}"); shift;;
+	--input-files)	shift
+			while [ $# -gt 0 -a "$1" != "$FIELDGREP_INPUTFILES_END" ]
+			do
+			    inputFilespecs+=("$1")
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --input-files must be concluded with '${FIELDGREP_INPUTFILES_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			if [ ${#inputFilespecs[@]} -eq 0 ]; then
+			    echo 'ERROR: --input-files must be followed by at least one FILE.'; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			;;
 	--invert-fields|-V)	shift; isInvertFields=t;;
 	--field-separator|-F)	shift; fsArgs=(-F "$1"); fieldSeparator="$1"; shift;;
 	--unbuffered|-u)	shift; isBuffered=''; grepBufferedArgs=(--line-buffered);;
@@ -184,7 +202,7 @@ NR == 1 {
     printf "0%s%s\n", OFS, OFS
     if (isUnBuffered) fflush()
 }
-' "${awkArgs[@]}" | \
+' "${inputFilespecs[@]}" | \
     grep "${grepRegexpDialectArgs[@]}" "${grepFixedStringsArgs[@]}" "${grepArgs[@]}" "${grepBufferedArgs[@]}" "${separatorGrepArgs[@]}" "${grepPatternArgs[@]}" | \
 awk "${fsArgs[@]}" \
     -v "isBuffered=$isBuffered" \
