fieldFilterNumber: Generalization: Support the understands protocol for command-line argument parsing delegation
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/fieldFilterNumber b/bin/fieldFilterNumber
--- a/bin/fieldFilterNumber
+++ b/bin/fieldFilterNumber
@@ -133,6 +133,22 @@ addComparison()
 }
 
 typeset -a fieldMapArgs=()
+option() { :; }
+parameter() { :; }
+parameterToSep() { :; }
+argCount() { :; }
+endOfOptionsAndParameters() { :; }
+noUnderstand() { :; }
+compareOp() { :; }
+typeset -A understandsSubtopics=()
+isUnderstandSubtopic() {
+    [ $# -gt 0 -a ${#understandsSubtopics[@]} -gt 0 ] || return 0
+    local subtopic; for subtopic
+    do
+	[ "${understandsSubtopics["$subtopic"]}" ] && return 0
+    done
+    return 1
+}
 while [ $# -ne 0 ]
 do
     case "$1" in
@@ -141,18 +157,37 @@ do
 			shift; getShortUsage "$@"; exit $?;;
 	--get-long-usage)
 			shift; getLongUsage "$@"; exit $?;;
+	--understand-for)
+			shift; understandsSubtopics["$1"]=t; shift;;
+	--understands)	shift
+			option() { isUnderstandSubtopic "$@" || exit 1; printf 1; exit 0; }
+			parameter() { isUnderstandSubtopic "$@" || exit 1; printf 2; exit 0; }
+			parameterToSep() { argCount "$@"; }
+			argCount() { local argCount="${1:?}"; shift; isUnderstandSubtopic "$@" || exit 1; printf $argCount; exit 0; }
+			endOfOptionsAndParameters() { exit 99; }
+			noUnderstand() { exit 1; }
+			compareOp() {
+			    if isUnderstandSubtopic compare-op; then
+				addComparison 0 "$1" "$2" 2>/dev/null \
+				    && { printf 2; exit 0; } \
+				    || exit 1
+			    else
+				exit 1
+			    fi
+			}
+			;;
 
-	-+([u]))	fieldMapArgs+=("$1"); shift;;
+	-+([u]))	fieldMapArgs+=("$1"); shift; option filter;;
 	--@(unbuffered))
-			fieldMapArgs+=("$1"); shift;;
-	-[F])		fieldMapArgs+=("$1" "${2?}"); shift; shift;;
+			fieldMapArgs+=("$1"); shift; option filter;;
+	-[F])		fieldMapArgs+=("$1" "${2?}"); shift; shift; option filter;;
 	--@(field-separator))
-			fieldMapArgs+=("$1" "${2?}"); shift; shift;;
-	--non-numeric)	shift; fieldMapArgs+=(--assign "nonNumericMode=${1:?}"); shift;;
-	?(-)+([0-9]))	addComparison "$1" "${2:?}" "${3:?}"; shift; shift; shift;;
-	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
-	*)		break;;
+			fieldMapArgs+=("$1" "${2?}"); shift; shift; option filter;;
+	--non-numeric)	shift; fieldMapArgs+=(--assign "nonNumericMode=${1:?}"); shift; parameter config;;
+	?(-)+([0-9]))	addComparison "$1" "${2:?}" "${3:?}"; shift; shift; shift; argCount 3 compare-expr;;
+	--)		endOfOptionsAndParameters; break;;
+	-*)		compareOp "$@"; { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		endOfOptionsAndParameters; break;;
     esac
 done
 if [ ${#comparisons[@]} -eq 0 ]; then
