Robustness: Print error if the same VALUE is used in multiple comparisons for a field [-]N
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/fieldFilterNumber b/bin/fieldFilterNumber
--- a/bin/fieldFilterNumber
+++ b/bin/fieldFilterNumber
@@ -57,7 +57,7 @@ storeComparison()
     local fieldNum="${1:?}"; shift
     local value="${1:?}"; shift
     local comparison="${1:?}"; shift
-    comparisons+=("comparisons[${fieldNum}][${value}]=\"${comparison}\"")
+    comparisons+=("if (comparisons[${fieldNum}][${value}] == \"\") { comparisons[${fieldNum}][${value}]=\"${comparison}\"; } else { printf(\"ERROR: Value %d already given in -%s comparison for field %d.\\n\", $value, comparisons[${fieldNum}][${value}], $fieldNum) > \"/dev/stderr\"; exit 2; }")
 }
 addComparison()
 {
